// Per-site brand configuration. Generated by scripts/gen-config.py from sites-config.json.
// Swap this file to rebrand the same template.
export const SITE = {
  // Identity
  brandName: "AZ Emergency Plumbing Co.",
  shortName: "AZ Emergency Plumbing",
  domain: "emergencyplumberaz.com",
  baseUrl: "https://emergencyplumberaz.com",
  founded: 2018,
  tagline: "24-hour emergency plumbing in Arizona. Real plumbers, real trucks, real pricing.",

  // Contact
  phone: "+16025550100",
  phoneDisplay: "(602) 555-0100",
  serviceArea: "Arizona — Phoenix metro, Tucson, and statewide",
  hours: "Mon-Sat 8am-8pm",

  // SEO
  niche: "emergency-plumbing",
  schemaSubtype: "Plumber",
  metaTitle: "AZ Emergency Plumbing Co. — 24/7 Plumber in Arizona",
  metaDescription: "24-hour emergency plumbing in Arizona. Real plumbers, real trucks, real pricing.",

  // Compliance
  disclaimerKey: "az-roc-contractor",

  // Cities — drives /[city]/ page generation
  cities: [
    { slug: "phoenix", name: "Phoenix", county: "Maricopa", pop: "1.61M", note: "5th-largest US city" },
    { slug: "mesa", name: "Mesa", county: "Maricopa", pop: "504K", note: "3rd-largest in AZ" },
    { slug: "tucson", name: "Tucson", county: "Pima", pop: "542K", note: "UA-anchored economy" },
    { slug: "chandler", name: "Chandler", county: "Maricopa", pop: "275K", note: "tech corridor anchored by Intel" },
    { slug: "scottsdale", name: "Scottsdale", county: "Maricopa", pop: "241K", note: "highest median home value in metro" },
    { slug: "gilbert", name: "Gilbert", county: "Maricopa", pop: "267K", note: "master-planned, fast-growing" },
    { slug: "glendale", name: "Glendale", county: "Maricopa", pop: "250K", note: "West Valley anchor" },
    { slug: "tempe", name: "Tempe", county: "Maricopa", pop: "195K", note: "ASU campus" },
    { slug: "peoria", name: "Peoria", county: "Maricopa", pop: "192K", note: "West Valley" },
    { slug: "surprise", name: "Surprise", county: "Maricopa", pop: "144K", note: "Sun City Festival 55+ community" },
    { slug: "yuma", name: "Yuma", county: "Yuma", pop: "95K", note: "border city; MCAS Yuma" },
    { slug: "buckeye", name: "Buckeye", county: "Maricopa", pop: "105K", note: "fastest-growing in West Valley" },
    { slug: "avondale", name: "Avondale", county: "Maricopa", pop: "90K", note: "raceway-anchored" },
    { slug: "goodyear", name: "Goodyear", county: "Maricopa", pop: "104K", note: "spring training; rapid growth" },
    { slug: "casa-grande", name: "Casa Grande", county: "Pinal", pop: "60K", note: "I-10 mid-point" },
    { slug: "flagstaff", name: "Flagstaff", county: "Coconino", pop: "76K", note: "Mountain town, NAU" },
    { slug: "prescott", name: "Prescott", county: "Yavapai", pop: "46K", note: "Mile-high, retiree heavy" },
    { slug: "sierra-vista", name: "Sierra Vista", county: "Cochise", pop: "44K", note: "Fort Huachuca military" },
    { slug: "kingman", name: "Kingman", county: "Mohave", pop: "33K", note: "Route 66 corridor, NW AZ" },
    { slug: "apache-junction", name: "Apache Junction", county: "Pinal", pop: "39K", note: "East Valley exurb" },
    { slug: "queen-creek", name: "Queen Creek", county: "Pinal", pop: "60K", note: "Fastest-growing AZ city" },
    { slug: "lake-havasu-city", name: "Lake Havasu City", county: "Mohave", pop: "57K", note: "Colorado River" },
    { slug: "bullhead-city", name: "Bullhead City", county: "Mohave", pop: "42K", note: "Across from Laughlin NV" },
    { slug: "anthem", name: "Anthem", county: "Maricopa", pop: "23K", note: "Master-planned, N. Phoenix" },
    { slug: "fountain-hills", name: "Fountain Hills", county: "Maricopa", pop: "23K", note: "Lakeside east of Scottsdale" },
    { slug: "litchfield-park", name: "Litchfield Park", county: "Maricopa", pop: "6K", note: "Wigwam Resort" },
  ],

  // Service sub-verticals — drives /situations/[vertical]/
  subVerticals: [
    { slug: "burst-pipe", name: "Burst Pipe Emergency", short: "Burst Pipe" },
    { slug: "water-heater", name: "Water Heater Repair & Replace", short: "Water Heater" },
    { slug: "drain-clog", name: "Drain Clog & Sewer Line", short: "Drain & Sewer" },
    { slug: "leak-detection", name: "Slab Leak Detection", short: "Slab Leak" },
    { slug: "gas-line", name: "Gas Line Repair", short: "Gas Line" },
    { slug: "garbage-disposal", name: "Garbage Disposal Repair", short: "Disposal" },
  ],

  // CTA rotation bank
  ctaBank: [
    "(602) 555-0100 — call us today.",
    "Call (602) 555-0100. We answer Mon-Sat 8am-8pm.",
    "(602) 555-0100 — talk to the owner directly.",
    "Call (602) 555-0100. No call centers, no transfers.",
    "(602) 555-0100 — same-day response when possible.",
  ],

  // Visual brand
  primaryColor: "#0d5c8a",
  accentColor: "#e63946",
  bgColor: "#f5f8fa",
  textColor: "#1a1a1a",
  fontHeading: "'Roboto Slab', Georgia, serif",
  fontBody: "system-ui, -apple-system, sans-serif",

  // Author / principal
  author: {
    name: "Mike",
    title: "Master Plumber & Owner",
    bio: "Mike is a Phoenix-based master plumber who started AZ Emergency Plumbing Co. after years watching homeowners get hit with inflated emergency invoices. He runs every job on upfront, flat-rate pricing with licensed techs across Arizona — no surprise fees, no call centers.",
  },

  // Social / OG
  ogImage: "/og-default.jpg",
} as const;

export type Cities = typeof SITE.cities;
export type City = typeof SITE.cities[number];
export type SubVertical = typeof SITE.subVerticals[number];
